# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import chatbot_pb2 as chatbot__pb2


class ChatBotServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Chatbot = channel.unary_unary(
        '/ChatBotService/Chatbot',
        request_serializer=chatbot__pb2.ReceivedMessage.SerializeToString,
        response_deserializer=chatbot__pb2.ResponsedMessage.FromString,
        )


class ChatBotServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Chatbot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatBotServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Chatbot': grpc.unary_unary_rpc_method_handler(
          servicer.Chatbot,
          request_deserializer=chatbot__pb2.ReceivedMessage.FromString,
          response_serializer=chatbot__pb2.ResponsedMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChatBotService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
